// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZjG0-aMz6vfBKM3zm0qeubsFzDC35G20',
    appId: '1:132638164965:web:c84f10302721043ccdd10c',
    messagingSenderId: '132638164965',
    projectId: 'fistra-project',
    authDomain: 'fistra-project.firebaseapp.com',
    storageBucket: 'fistra-project.firebasestorage.app',
    measurementId: 'G-SF7SLN77T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgV8G5d4W5A5NC4XtonKgsbrESPSx3SsY',
    appId: '1:132638164965:android:fd4d2876e682ed4acdd10c',
    messagingSenderId: '132638164965',
    projectId: 'fistra-project',
    storageBucket: 'fistra-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY9CDJ3LLGvZkzkwhe2FRBabYafwbR9_c',
    appId: '1:132638164965:ios:e876a5a4bc0c1774cdd10c',
    messagingSenderId: '132638164965',
    projectId: 'fistra-project',
    storageBucket: 'fistra-project.firebasestorage.app',
    iosBundleId: 'com.example.fistra1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY9CDJ3LLGvZkzkwhe2FRBabYafwbR9_c',
    appId: '1:132638164965:ios:e876a5a4bc0c1774cdd10c',
    messagingSenderId: '132638164965',
    projectId: 'fistra-project',
    storageBucket: 'fistra-project.firebasestorage.app',
    iosBundleId: 'com.example.fistra1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZjG0-aMz6vfBKM3zm0qeubsFzDC35G20',
    appId: '1:132638164965:web:0691bae976575626cdd10c',
    messagingSenderId: '132638164965',
    projectId: 'fistra-project',
    authDomain: 'fistra-project.firebaseapp.com',
    storageBucket: 'fistra-project.firebasestorage.app',
    measurementId: 'G-XE7M5WPH2T',
  );
}
